### ISSUE TITLE
Switch away from WPCS VIP standard

### ISSUE THREAD

**Issue by GaryJones** [Automattic/vip-go-wpcom-compat#20]
The `WordPress-VIP` coding standard from WPCS is deprecated. It is currently referenced in the `Makefile`.

It would be better to use the `WordPress-VIP-Go` standard from [VIPCS](https://github.com/Automattic/VIP-Coding-Standards/) instead.

Better yet, use `WordPress-Extras` + `WordPress-VIP-Go` :-)

**Comment by joshbetz** [comment]
Hi @GaryJones. Would you be able to help with this? I noticed builds are currently broken because the WordPress-VIP coding standard was removed from WPCS.

I tried switching to the new standard, but am getting an error:

```
Fatal error: require_once(): Failed opening required '/tmp/wpcs/WordPress/PHPCSAliases.php'
```

**Comment by GaryJones** [comment]
Instead of relying on WPCS `master`, checkout the `1.2.1` tag instead. 

Whilst you're at it, ensure the `0.4.0` tag of VIPCS is checked out.

Now that breaking changes are happening in both projects (but they both follow semantic versioning), then relying on `master` isn't a good choice.

**Comment by joshbetz** [comment]
Aha! That makes sense. Thank you!
