### ISSUE TITLE
🐛 `writing-helper` plugin is not compatible with PHP 8.0

### ISSUE THREAD

**Issue by hbhalodia** [Automattic/vip-go-wpcom-compat#47]
**Issue**

- The `writing-helper` plugin used in `vip-go-wpcom-compact` is not up to date with [writing-helper](https://github.com/Automattic/writing-helper/)
- The sites with the latest PHP 8.0 face the fatal error from the `writing-helper` plugin which is solved with the latest update.
- Need to update the `writing-helper` plugin by taking the plugin from the latest master branch, as VIP sites that use the `vip-go-wpcom-compact` plugin and want to upgrade to PHP their site to PHP 8.0.

**Comment by rebeccahum** [comment]
Looks like it's been merged now, closing!
